# Generated by Django 2.2.2 on 2019-07-03 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_draft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='draft',
            new_name='is_draft',
        ),
    ]
