# Generated by Django 2.2.2 on 2019-07-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='background_image',
            field=models.ImageField(default='a', upload_to=''),
            preserve_default=False,
        ),
    ]
