# Generated by Django 2.2.3 on 2019-07-09 09:35

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='background_image',
            field=models.ImageField(upload_to=blog.models.get_upload_path),
        ),
    ]
