# Generated by Django 2.2.3 on 2019-07-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190709_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
